>DELLA4A-Kronos-sg2-F3R3
GCTCTGTGGTGGAGGCTGCTCCGCCGGTCGCGGCCGGGGCCAACGCGCCCGCGCTGCCGGTCGTCGTGGTCGACACGCAGGAGGCCGGGATTCGGCTGGTGCACGCGCTGCTGGCCTGCGCGGAGGCCGTGCAGCAGGAGAACTTCTCTGCCGCGGAGGCGCTGGTGAAGCAGATACCCTTGCTGGCCG
>DELLA4B-Kornos-sg2-F3R3
GCTCTGTGGTGGAGGCTGCCCCGCCGGTGGCCGCCGCGGCCGGTGCGCCCGCGCTGCCGGTCGTCGTGGTCGACACGCAGGAGGCCGGGATTCGGCTGGTGCACGCGCTGCTGGCGTGCGCAGAGGCCGTGCAGCAGGAGAACTTCTCTGCCGCGGAGGCGCTGGTGAAGCAGATACCCTTGCTGGCCG

### DELLA
# sg1
CRISgov5 ../references.fasta della-sg1-4A DELLA4A-Kronos  GGGAGGGGGAGGA AGAAGCTGGAGCA GCTGGCGGCGCTCGGGTACA
CRISgov5 ../references.fasta della-sg1-4B DELLA4B-Kronos  GGGAGGGGGAGGA AGAAGCTGGAGTA GCTGGCGGCGCTCGGGTACA

# sg2
CRISgov5 ../references.fasta della-sg2-4A DELLA4A-Kronos CGCTGCCGGTCGT CTGCGCGGAGGCCG GCAGGAGGCCGGGATTCGGC
CRISgov5 ../references.fasta della-sg2-4B DELLA4B-Kronos CGCTGCCGGTCGT GTGCGCAGAGGCCG GCAGGAGGCCGGGATTCGGC


# combine results
awk '{print FILENAME","$0}' *.csv > Junli_merged_results_crisgov5.csv

# get the fasta number
getclip | cut -f1 -d"_" | putclip
